### ISSUE TITLE
Option to skip Vaadin theme compilation in vaadin-maven-plugin

### ISSUE THREAD

**Issue by focbenz** [vaadin/maven-plugin#101]
As a developer on a larger multi-module project I would like to skip Vaadin Widget Set compilation to save time in a specified Maven profile.

As discussed in the forum thread here (https://vaadin.com/forum#!/thread/15940338) it would be nice to have an option to skip Widget Set compilation which can be used on Maven command line or a property like the GWT compiler property:
- gwt.compiler.skip

Background would be a "fast" profile like this skipping all compilation:
```
<profile>
    <id>fast</id>
    <properties>
        <!-- skip all tests -->
        <skipTests>true</skipTests>
        <!-- skip generating the Javadoc -->
        <maven.javadoc.skip>true</maven.javadoc.skip>
        <!-- skip the Maven source procedure -->
        <source.skip>true</source.skip>
        <!-- skip the Git commit ID plugin -->
        <git.commit-id.skip>true</git.commit-id.skip>
        <!-- skip the license check (for e.g. GPL) -->
        <skipLicenseCheck>true</skipLicenseCheck>
        <!-- skip compiling the Vaadin widget set -->
        <gwt.compiler.skip>true</gwt.compiler.skip>
        <!-- skip compiling main java -->
        <maven.main.skip>true</maven.main.skip>
    </properties>
</profile>
```

Remaining items to skip are:

> [INFO] --- vaadin-maven-plugin:8.1.0.alpha8:compile-theme (default) @ module ---
> [INFO] Updating theme VAADIN\themes\modlayout
> [INFO] Theme "VAADIN\themes\modlayout" compiled
> [INFO] Updating theme VAADIN\themes\modlayout
> [INFO] Theme "VAADIN\themes\modlayout" compiled

Current workaround is like Marco specified to just bind the Vaadin Maven Plugin to a non-existent phase.

**Comment by avackova** [comment]
Skipping theme compolation is important. It's impossible to use custom favicon with existing theme :-(

**Comment by focbenz** [comment]
No longer relevant. Closing the issue / request and workaround is known.
