### ISSUE TITLE
Production Build fails when called from bibucket pipeline

### ISSUE THREAD

**Issue by DonAscon** [vaadin/maven-plugin#115]
When I use the plugin to build production mode locally on Windows, its fine.

But on the build pipeline the output of the plugin is

```[INFO] --- vaadin-maven-plugin:10.0.6:package-for-production (default) @ hoffice ---
[WARNING] The translated URL 'frontend://bower_components/vaadin-upload/theme/lumo/vaadin-upload-file.html' has no corresponding file on the filesystem, the file is addressed by path='/opt/atlassian/pipelines/agent/build/target/frontend/bower_components/vaadin-upload/theme/lumo/vaadin-upload-file.html'
[INFO] Installing required frontend tools to '/opt/atlassian/pipelines/agent/build/target'
[INFO] Installing node version v8.11.1
[INFO] Downloading https://nodejs.org/dist/v8.11.1/node-v8.11.1-linux-x64.tar.gz to /opt/atlassian/pipelines/agent/build/target/cache/node-v8.11.1-linux-x64.tar.gz
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly
[INFO] Unpacking /opt/atlassian/pipelines/agent/build/target/cache/node-v8.11.1-linux-x64.tar.gz into /opt/atlassian/pipelines/agent/build/target/node/tmp
[INFO] Copying node binary from /opt/atlassian/pipelines/agent/build/target/node/tmp/node-v8.11.1-linux-x64/bin/node to /opt/atlassian/pipelines/agent/build/target/node/node
[INFO] Installed node locally.
[INFO] Installing Yarn version v1.6.0
[INFO] Downloading https://github.com/yarnpkg/yarn/releases/download/v1.6.0/yarn-v1.6.0.tar.gz to /opt/atlassian/pipelines/agent/build/target/cache/yarn-v1.6.0.tar.gz
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly
Oct 21, 2018 2:27:29 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: has_recent_activity=1; path=/; expires=Sun, 21 Oct 2018 15:27:29 -0000". Invalid 'expires' attribute: Sun, 21 Oct 2018 15:27:29 -0000
Oct 21, 2018 2:27:29 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Thu, 21 Oct 2038 14:27:29 -0000; secure; HttpOnly". Invalid 'expires' attribute: Thu, 21 Oct 2038 14:27:29 -0000
[INFO] Unpacking /opt/atlassian/pipelines/agent/build/target/cache/yarn-v1.6.0.tar.gz into /opt/atlassian/pipelines/agent/build/target/node/yarn
[INFO] Installed Yarn locally.
[INFO] Running 'yarn install' in /opt/atlassian/pipelines/agent/build/target
[ERROR] /opt/atlassian/pipelines/agent/build/target/node/yarn/dist/bin/yarn: exec: line 31: node: Permission denied
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26.016 s
[INFO] Finished at: 2018-10-21T14:27:30Z ```
```

My pipeline configuration:
`  - step:
      image: maven:3.5-jdk-8-alpine
      name: Build
      caches:
      - maven
      script:
      - apk update
      - mvn -e -Pproduction verify package  `

It is doing nothing different from locally.

The configuration of the plugin is
`           <build>
                <plugins>
                    <plugin>
                        <groupId>com.vaadin</groupId>
                        <artifactId>vaadin-maven-plugin</artifactId>
                        <version>${vaadin.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>copy-production-files</goal>
                                    <goal>package-for-production</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>`

Using Vaadin version 10.0.6

I think there is some chmod +x missing, and I assume my problem to be related to this https://github.com/eirslett/frontend-maven-plugin/issues/743

**Comment by pleku** [comment]
Hi. What if you try it with a newer plugin version? Because https://github.com/vaadin/flow/pull/4543 added a way to configure a local install of node & yarn, I have no bitbucket experience on how to get it there but I imagine it is possible...

Note though that you'll have to switch the plugin name to `flow-maven-plugin` to be able specify this version to it (`vaadin-maven-plugin` is the same thing just repackaged in the platform build so it has the same version as the platform release).

Another thing is that recently we added autodetecting of those too https://github.com/vaadin/flow/pull/4543, that is available in Vaadin 12.0.0.beta1 or `flow-maven-plugin` 1.2.0

**Comment by DonAscon** [comment]
Seems to be working with 1.2.0 out of the box. Great! Thank you!

**Comment by pleku** [comment]
Great to hear that.
